# .github/workflows/pages-deploy.yml
# Deploys repository root to GitHub Pages on push to main
# Requires no additional secrets for standard Pages deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'        # deploy repo root; adjust to './docs' if you use /docs
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
